### ISSUE TITLE
plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [pgipper/Beeline#1]
Please remove .pyc files they are generated automatically when you install the plugin and add metadata.txt

**Comment by pgipper** [comment]
Okay, done! Thanks for reviewing.

**Comment by pgipper** [comment]
@NyakudyaA Do i have to resubmit the plugin? I wonder why it doesnt get approved after i fixed as requested. Sorry, i am new to the process.

**Comment by NyakudyaA** [comment]
Hi @Ah4b I will look at it and approve if there is no other plugin or QGIS functionality that does the same. Approval and testings is a volunteering thing, I always aim to test it first. I will approve either today or tommorow

**Comment by pgipper** [comment]
Hi @NyakudyaA 
Awesome, thanks. I looked for this functionality in plugins, too, but didn't find any, which is a bit weird since it feels like a basic thing. The idea came up when i was doing chapter 12 _Visualising Global Connections_ in the book QGIS Map Design by Graser and Peterson (2016) where they construct pseudo-beelines in a rather complicated fashion.

I am aware that this is very basic, but i think it's a good start and there is lots of room for expansions like adding attributes etc. and making full use of the geographiclib potential.

I know all the testing is voluntary and i appreciate it a lot (I might join once i am more into the QGIS World). But since this is my first submission i just wondered if i missed something that i had to do. Theres no hurry.
