### ISSUE TITLE
It looks Like You Are Duplicating Shape Tools Functions

### ISSUE THREAD

**Issue by hamiltoncj** [pgipper/Beeline#3]
As others have said there is a Raster error so I have not been able to get it to run, but additionally from the description it looks like you have duplicated functionality of the Shape Tools plugin. Please try to not to duplicate effort and if what you have is a slight variation please try to work with other developers to create better tools and not duplicate effort.

I would also suggest that you don't create unrealistic votes for your plugin.

**Comment by pgipper** [comment]
Yes, i also wondered that there was no such plugin already available. I even checked Shape Tools before, and i only found it with a csv table input i remember. I see that there was alot done though, and any further effort will be on the ShapeTools rather than Beeline if i miss a funtionality.

The raster error is fixed. Votes too. I blame colleagues and students. But please vote :)
